#!/bin/bash


find_largest() {
    
    read -p "Enter the first number: " num1
    read -p "Enter the second number: " num2
    read -p "Enter the third number: " num3

    
    largest=$num1

    
    if [ $num2 -gt $largest ]; then
        largest=$num2
    fi

   
    if [ $num3 -gt $largest ]; then
        largest=$num3
    fi


    echo "The largest number is: $largest"
}

find_largest

OUTPUT:
Enter the first number: 3
Enter the second number: 5
Enter the third number: 6
The largest number is: 6
